environments:
  - name: WING-SIT
    BASE_URL: "https://thkcore-wing-sit.blockfint.com"
    EMAIL: "test_email_app1@email.com"
    PASSWORD: "test_password_app1"

  - name: SIT
    BASE_URL: "https://moneydd-sit.thinkerfint.com"
    EMAIL: "moneydd-sit@thinkerfint.com"
    PASSWORD: "moneydd-sit"

  - name: DEV
    BASE_URL: "https://moneydd-dev.thinkerfint.com"
    EMAIL: "moneydd-dev@thinkerfint.com"
    PASSWORD: "moneydd-dev"

  - name: UAT
    BASE_URL: "https://moneydd-uat.thinkerfint.com"
    EMAIL: "moneydd-uat@thinkerfint.com"
    PASSWORD: "moneydd-uat"

  - name: PERF
    BASE_URL: "https://moneydd-perftest.thinkerfint.com"
    EMAIL: "moneydd-perftest@thinkerfint.com"
    PASSWORD: "moneydd-perftest"

  - name: PROD
    BASE_URL: "https://moneydd.thinkerfint.com"
    EMAIL: "moneydd-prod@thinkerfint.com"
    PASSWORD: "moneydd-prod"

endpoints-config:
  - name: "Answer Question"
    endpoint: "/question-taskpool/api/v1/answer-question"
    method: "POST"
  - name: "Submit Case"
    endpoint: "/case-datasources/api/v1/cases/submit"
    method: "POST"
  - name: "A-Score"
    endpoint: "/ascore-service/api/v1/ascore"
    method: "POST"
  - name: "Get Case Detail"
    endpoint: "/question-taskpool/api/v1/get-case-detail-all-task"
    method: "POST"
  - name: "Create Field"
    endpoint: "/universe/api/v1/create_field"
    method: "POST"
  - name: "Update Field"
    endpoint: "/universe/api/v1/update_field"
    method: "POST"

products:
  Product1: "moneydd.pLoan"
  Product2: "moneydd.nanoLoan"
  Product3: "test.aScore"
